---
NB_URL: "http://185.121.88.235:8000"
NB_USERNAME: "admin"
NB_PASSWORD: "CATNIX49"
NB_TOKEN: "a4fffd4bcf28427e8139179e655330c519be7c97"
DEVICE_PORT: "17140"
DEVICE_USERNAME: "catnix"
DEVICE_PASSWORD: "CATNIX49"
